'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Track
    Public Property TrackID As Integer
    Public Property TrackName As String
    Public Property Artist As String
    Public Property Genre As String
    Public Property DanceClub As Nullable(Of Integer)
    Public Property PopBar As Nullable(Of Integer)
    Public Property PartyClub As Nullable(Of Integer)

End Class
