//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jukebox.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VenueTrack
    {
        public int VoteID { get; set; }
        public int VenueID { get; set; }
        public int TrackID { get; set; }
        public int ArtistID { get; set; }
        public int GenreID { get; set; }
        public int VenueTrackID { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual Track Track { get; set; }
        public virtual Venue Venue { get; set; }
        public virtual Vote Vote { get; set; }
    }
}
